# frontend/Dockerfile.front

# Etapa de build con Node
FROM node:18-alpine as build
WORKDIR /app

# Copiamos deps e instalamos
COPY package*.json ./
RUN npm install

# Copiamos el resto y construimos
COPY . .
RUN npm run build

# Etapa final (Nginx) para servir la app
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
