version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root 
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - prestabanco-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - prestabanco-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=PrestaBanco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prestabanco-network

  backend:
    build:
      context: ./devsecops-prestabanco-backend
      dockerfile: Dockerfile
    container_name: prestabanco-backend
    restart: always
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/PrestaBanco
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123admin
    depends_on:
      - postgres
    networks:
      - prestabanco-network

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data:

networks:
  prestabanco-network:
    driver: bridge
